### ISSUE TITLE
v1.11 is still showing as the current version in CPAN

### ISSUE THREAD

**Issue by ssimms** [CPAN-Adoptable-Modules/business-us-usps-webtools#2]
I can't tell where the problem is, but MetaCPAN and http://www.cpan.org/modules/01modules.index.html are still showing 1.11 (from 2007) as the most recent version of this module.  Is this something you can fix?

**Comment by MartinMcGrath** [comment]
Similar to https://github.com/davorg/tie-hash-cannabinol/issues/1 v1.11 shows up in [02package.details.txt](http://www.cpan.org/modules/02packages.details.txt)

**Comment by briandfoy** [comment]
I think this is because ADOPTME didn't make me a comaintainer on one of the modules so PAUSE did not index the distro.
